import Head from "next/head"
import { useRouter } from "next/router"
import Container from "../components/Container"
import Footer from "../components/Footer"
import Header from "../components/Header"
import SearchResults from "../components/SearchResults"
import SideContainer from "../components/SideContainer"
import dummyData from "../data/dummyData"

export default function Search({ results }) {
	const router = useRouter()
	return (
		<Container>
			<Head>
				<title>{router.query.q} Search</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<SideContainer>
				<SearchResults results={results} />
			</SideContainer>
			<Footer />
		</Container>
	)
}

export async function getServerSideProps(context) {
	const useDummyData = false
	const startIndex = context.query.start || 0

	const data = useDummyData
		? dummyData
		: await fetch(
				`https://www.googleapis.com/customsearch/v1?key=${process.env.GOOGLE_API}&cx=${process.env.CONTEXT_KEY}&q=${context.query.q}&start=${startIndex}`
		  ).then((res) => res.json())

	return {
		props: {
			results: data,
		},
	}
}
